accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.sign_in, name='login'),
    url(r'^logout/$', views.sing_out, name='logout'),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^profile/$', views.profile, name='profile'),
]

papers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<paper_id>[0-9]+)/$', views.show, name='show'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<paper_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<paper_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<comment_id>[0-9]+)/comment/delete$', views.delete_comment,
        name='delete_comment'),
]

wiki_fiction/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import welcome

urlpatterns = [
    url(r'^$', welcome, name='welcome'),
    url(r'^papers/', include('papers.urls', namespace='papers')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'welcome' %}">Project name</a>
        </div>
        {% block navbar %}
            <div id="navbar" class="collapse navbar-collapse">
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'papers:index' %}">Papers</a></li>
                    </ul>
                    <div class="navbar-form navbar-right">
                        <a class="btn btn-success" href="{% url 'accounts:logout' %}">Sign out</a>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <li><p class="navbar-text">Welcome, {{ user.get_full_name|default:"Mr. Nobody" }}!</p></li>
                    </ul>
                {% else %}
                    {% include 'partials/login_form.html' %}
                {% endif %}
            </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
</nav>

templates/partials/login_form.html
<form action="{% url 'accounts:login' %}" method="post" class="navbar-form navbar-right">
    {% csrf_token %}
    <div class="form-group">
      <input name="username" type="text" placeholder="Email or Username" class="form-control">
    </div>
    <div class="form-group">
      <input name="password" type="password" placeholder="Password" class="form-control">
    </div>
    <button type="submit" class="btn btn-success">Sign in</button>
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
</form>

templates/partials/massages.html
{% if messages %}
    {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }} {% if message.tags = 'error' %}alert-danger{% endif %}"{% endif %}>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}