accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.sign_in, name='login'),
    url(r'^logout/$', views.sing_out, name='logout'),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^profile/$', views.profile, name='profile'),
]

papers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<paper_id>[0-9]+)/$', views.show, name='show'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<paper_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<paper_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<comment_id>[0-9]+)/comment/delete$', views.delete_comment,
        name='delete_comment'),
]

wiki_fiction/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import welcome

urlpatterns = [
    url(r'^$', welcome, name='welcome'),
    url(r'^papers/', include('papers.urls', namespace='papers')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars',
                               default='avatars/default-avatar.jpg')

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from django import forms
from .models import CustomUser


class CustomUserForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("username",)


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "avatar",
        )

    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
        'password_incorrect': _("Your old password was entered incorrectly. "
                                "Please enter it again."),
    }
    new_password1 = forms.CharField(label=_("New password"),
                                    widget=forms.PasswordInput, required=False)
    new_password2 = forms.CharField(label=_("New password confirmation"),
                                    widget=forms.PasswordInput, required=False)

    old_password = forms.CharField(label=_("Old password"),
                                   widget=forms.PasswordInput)

    def clean_old_password(self):
        """
        Validates that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.instance.check_password(old_password):
            raise forms.ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )
        return old_password

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

    def save(self, commit=True):
        super().save(commit=False)
        if self.cleaned_data['new_password1']:
            self.instance.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.instance.save()
        return self.instance

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth import update_session_auth_hash
from stronghold.decorators import public
from .forms import CustomUserForm, UserProfileForm


@public
def welcome(request):
    if 'next' in request.GET:
        if not request.user.is_authenticated():
            messages.error(request, "You're should login before continue.")
        else:
            messages.error(request, "Sorry, but you do not have permission for \
                                                                this action.")
    return render(request, 'accounts/welcome.html')


@public
def sign_in(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    to = 'welcome'
    if user is not None:
        if user.is_active:
            login(request, user)
            messages.success(request, "You're successfully sign in!")
            to = request.POST.get('next') or to
        else:
            messages.warning(request, "Sorry, but your account disabled.")
    else:
        messages.warning(request, "Invalid login.")
    return redirect(to)


def sing_out(request):
    logout(request)
    messages.success(request, "You're successfully sign out!")
    return redirect('welcome')


@public
def sign_up(request):
    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(username=username, password=password)
            if user.is_active:
                login(request, user)
                messages.success(request, "You're successfully sign up!")
            else:
                messages.warning(request, "Sorry, but your account disabled \
                                                                        yet.")
            return redirect('welcome')
    else:
        form = CustomUserForm()
    return render(request, 'accounts/sign_up.html', {'form': form})


def profile(request):
    form = UserProfileForm(request.POST or None, request.FILES or None,
                           instance=request.user)

    if request.method == 'POST' and form.is_valid():
        form.save()
        update_session_auth_hash(request, form.instance)
        messages.success(request, "Your profile was successfully updated!")
        return redirect('welcome')

    return render(request, 'accounts/profile.html', {'form': form})

accounts/templates/accounts/accounts_layout.html
{% extends "base_layout.html" %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}

accounts/templates/accounts/layout.html
{% extends "base.html" %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
    {% include "accounts/partials/profile_form.html" %}
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends "accounts/layout.html" %}

{% block title %}Registration{% endblock %}

{% block header %}
    {% include 'accounts/partials/header.html' %}
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% include "libs/bootstrap_form_snippet.html" %}
        <input type="submit" value="Save" class="btn btn-primary"/>
    </form>
{% endblock %}

accounts/templates/accounts/welcome.html
{% extends "accounts/layout.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="starter-template">
        <h1>Hello, {{ user.get_full_name | default:"Mr. Nobody" }}!</h1>
        {% if not user.is_authenticated %}
        <p class="lead">
                You have to login or
                <a href="{% url 'accounts:sign_up' %}">sign up</a>
                before continue :)
        </p>
        {% endif %}
    </div>
{% endblock %}