papers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<paper_id>[0-9]+)/$', views.show, name='show'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<paper_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<paper_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<comment_id>[0-9]+)/comment/delete$', views.delete_comment,
        name='delete_comment'),
]

wiki_fiction/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import welcome

urlpatterns = [
    url(r'^$', welcome, name='welcome'),
    url(r'^papers/', include('papers.urls', namespace='papers')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

papers/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator


class Tag(models.Model):
    name = models.CharField(max_length=30, db_index=True)

    def __str__(self):
        return self.name


class Paper(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='papers')
    tags = models.ManyToManyField(Tag, related_name='papers')
    title = models.CharField(max_length=30, db_index=True)
    text = models.TextField()
    rating = models.FloatField(
        null=False,
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def tag_names(self):
        return ', '.join([tag.name for tag in self.tags.all()])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('papers:show', args=[self.pk])


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments')
    paper = models.ForeignKey(Paper, related_name='comments')
    text = models.TextField()
    rating = models.FloatField(
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s..." % self.text[:10]

papers/forms.py
from django import forms
from libs.fields import ChosenSelect
from .models import Paper, Comment


class PaperForm(forms.ModelForm):

    class Meta:
        model = Paper
        fields = [
            'tags',
            'title',
            'text',
        ]
        widgets = {
            'tags': ChosenSelect(
                attrs={'class': 'chosen-select', 'id': 'tags'}
            )
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = [
            'text',
            'rating',
        ]

papers/views.py
# from django.contrib.auth.decorators import permission_required
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import Paper, Comment
from .forms import PaperForm, CommentForm


def index(request):
    papers = Paper.objects.all().select_related(
        'user').prefetch_related('tags').order_by('id')

    paginator = Paginator(papers, 10)
    page = request.GET.get('page')
    try:
        papers = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        papers = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        papers = paginator.page(paginator.num_pages)

    return render(request, 'papers/index.html',
                  {'paper_list': papers})


def show(request, paper_id):
    try:
        paper = Paper.objects.prefetch_related(
            'comments__user').get(pk=paper_id)
    except Paper.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.paper = paper
            comment.save()
            messages.success(request, 'Comment was successfully added')
            return redirect(paper)
    else:
        comment_form = CommentForm()

    return render(request, 'papers/show.html',
                  {'paper': paper, 'comment_form': comment_form})


# @permission_required('papers.delete_comment')
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    messages.success(request, 'Comment was successfully deleted')
    return redirect(comment.paper)


# @permission_required('papers.add_paper')
def new(request):
    if request.method == 'POST':
        form = PaperForm(request.POST)
        if form.is_valid():
            paper = form.save(commit=False)
            paper.user = request.user
            paper.save()
            form.save_m2m()

            messages.success(request, 'Paper was successfully created')
            return redirect(paper)
    else:
        form = PaperForm()

    return render(request, 'papers/new.html', {'form': form})


# @permission_required('papers.change_paper')
def edit(request, paper_id):
    paper = get_object_or_404(Paper, pk=paper_id)
    form = PaperForm(request.POST or None, instance=paper)

    if request.method == 'POST' and form.is_valid():
        form.save()
        messages.success(request, 'Paper was successfully updated')
        return redirect(paper)

    return render(request, 'papers/edit.html', {'form': form})


# @permission_required('papers.delete_paper')
def delete(request, paper_id):
    paper = get_object_or_404(Paper, pk=paper_id)
    paper.delete()
    messages.success(request, 'Paper was successfully deleted')

    return redirect(reverse('papers:index'))

papers/templates/papers/base_papers.html
{% extends "layouts/base.html" %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'papers/style.css' %}">
{% endblock %}

papers/templates/papers/edit.html
{% extends "papers/layout.html" %}

{% block title %}Edit Paper{% endblock %}

{% block content %}
    {% include 'papers/partials/paper_form.html' %}
{% endblock %}

papers/templates/papers/form.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" class="btn btn-primary"/>
</form>

papers/templates/papers/index.html
{% extends "papers/layout.html" %}

{% block title %}Papers{% endblock %}

{% block content %}
    {% if perms.papers.add_paper %}
        <p><a href="{% url 'papers:new' %}" class="btn btn-primary">Add paper</a></p>
    {% endif %}
    {% if paper_list %}
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="col-md-1">#</th>
              <th class="col-md-1">Title</th>
              <th class="col-md-2">Text</th>
              <th class="col-md-2">Tags</th>
              <th class="col-md-1">Rating</th>
              <th class="col-md-2">Created at</th>
              <th class="col-md-1">User</th>
              <th class="col-md-2"></th>
            </tr>
          </thead>
          <tbody>
            {% for paper in paper_list %}
                <tr>
                  <th scope="row">{{ paper.id }}</th>
                  <td>{{ paper.title }}</td>
                  <td>{{ paper.text }}</td>
                  <td>{{ paper.tag_names }}</td>
                  <td>{{ paper.rating | floatformat }}</td>
                  <td>{{ paper.created_at|date:"d b, Y" }}</td>
                  <td>{{ paper.user.get_full_name }}</td>
                  <td>
                      <a href="{% url 'papers:show' paper.id %}" class="btn btn-sm btn-success">Show</a>
                      {% if perms.papers.change_paper %}
                          <a href="{% url 'papers:edit' paper.id %}" class="btn btn-sm btn-warning">Edit</a>
                      {% endif %}
                      {% if user.is_superuser or perms.papers.delete_paper and user.id == paper.user_id %}
                        <a href="{% url 'papers:delete' paper.id %}" class="btn btn-sm btn-danger">Delete</a>
                      {% endif %}
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
            {% include 'libs/pagination.html' with list=paper_list %}
    {% else %}
        <p>No papers are available.</p>
    {% endif %}
{% endblock %}

papers/templates/papers/layout.html
{% extends "base.html" %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'papers/style.css' %}">
{% endblock %}

papers/templates/papers/new.html
{% extends "papers/layout.html" %}

{% block stylesheets %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}

{% block title %}New Paper{% endblock %}

{% block content %}
    {% include 'papers/partials/paper_form.html' %}
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    {{ form.media.js }}
{% endblock %}

papers/templates/papers/papers_layout.html
{% extends "base_layout.html" %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'papers/style.css' %}">
{% endblock %}

papers/templates/papers/show.html
{% extends "papers/layout.html" %}

{% block title %}Paper{% endblock %}

{% block content %}
    <h3 class="text-center">Paper</h3>
    <dl class="dl-horizontal">
        <dt>Title</dt>
        <dd>{{ paper.title }}</dd>
        <dt>Rating</dt>
        <dd>{{ paper.rating | floatformat }}</dd>
        <dt>Text</dt>
        <dd>{{ paper.text }}</dd>
        <dt>Tags</dt>
        <dd>{{ paper.tag_names }}</dd>
        <dt>Created at</dt>
        <dd>{{ paper.created_at|date:"d b, Y" }}</dd>
        <dt>User</dt>
        <dd>{{ paper.user.get_full_name | default:"Mr. Nobody" }}</dd>
    </dl>
{#    <a href="{% url 'papers:index' %}" class="btn btn-primary">Go to list</a>#}
    {% if paper.comments.all %}
        <h3 class="text-center">Comments</h3>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="col-md-1">#</th>
              <th class="col-md-2">User</th>
              <th class="col-md-7">Text</th>
              <th class="col-md-1">Rating</th>
              <th class="col-md-1"></th>
            </tr>
          </thead>
          <tbody>
            {% for comment in paper.comments.all %}
                <tr>
                  <th scope="row">{{ comment.id }}</th>
                  <td>{{ paper.user.get_full_name | default:"Mr. Nobody" }}</td>
                  <td>{{ comment.text }}</td>
                  <td>{{ comment.rating | floatformat }}</td>
                  <td>
                      {% if perms.papers.delete_comment %}
                          <a href="{% url 'papers:delete_comment' comment.id %}" class="btn btn-sm btn-danger">Delete</a>
                      {% endif %}
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
    {% endif %}
    <h3 class="text-center">Add comment</h3>
    {% include 'papers/partials/comment_form.html' %}
{% endblock %}

papers/templates/papers/welcome.html
{% extends "layouts/base.html" %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'papers/css/welcome.css' %}">
{% endblock %}
{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="starter-template">
        <h1>Hello!</h1>
        <p class="lead">Don't worry. Be happy.</p>
    </div>
{% endblock %}